# 2.1.13 - LAB Formatting the output

###################
print("original version:")
###################
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
###################
print("with fewer 'print()' invocations:")
###################
print("    *\n   * *\n  *   *\n *     *\n***   ***")
print("  *   *\n  *   *\n  *****")
###################
print("higher:")
###################
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")
###################
print("doubled:")
###################
print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("******     ******"*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *******     "*2)

print("triple print:")
###################
print("        *        "*3)
print("       * *       "*3)
print("      *   *      "*3)
print("     *     *     "*3)
print("    *       *    "*3)
print("   *         *   "*3)
print("  *           *  "*3)
print(" *             * "*3)
print("******     ******"*3)
print("     *     *     "*3)
print("     *     *     "*3)
print("     *     *     "*3)
print("     *     *     "*3)
print("     *     *     "*3)
print("     *     *     "*3)
print("     *******     "*3)